PrecisoPRO/Controllers/BuscarcndsController.cs
using Microsoft.AspNetCore.Mvc;
using PrecisoPRO.Interfaces;
using PrecisoPRO.Models;
using PrecisoPRO.Models.ViewModels;

namespace PrecisoPRO.Controllers
{
    public class BuscarcndsController : Controller
    {
        //contexto do banco de dados
        private readonly IEmpresaRepository _empresaRepository;
        private readonly IEstadoRepository _estadoRepository;
 
        IEnumerable<Empresa>? listaEmpresas; //Lista enumerada
        IEnumerable<Estado>? listaEstados; //lista de estados

        IEnumerable<AssociarEmpUf>? listaAssociarEmpUF;
        int contSalvos = 0;

        //CONSTRUTOR
        public BuscarcndsController(IEmpresaRepository empresaRepository, IEstadoRepository estadoRepository)
        {
            _empresaRepository = empresaRepository;
            _estadoRepository = estadoRepository;
           
           
        }
        public async Task<IActionResult> Index(string cnpj, string ie, string  finalidade="CADASTRO")
        {
            

            return View();
        }

        


      
    }
}

PrecisoPRO/Controllers/CndEstadualController.cs
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using PrecisoPRO.Interfaces;
using PrecisoPRO.Models;
using PrecisoPRO.Repository;
using PrecisoPRO.Services;
using System.Xml;
using X.PagedList;

namespace PrecisoPRO.Controllers
{
    public class CndEstadualController : Controller
    {
        HttpClient httpClient = new HttpClient();
      
        //Serviço API Estadual
        private readonly SefazToApiService _sefazToApiService;
        private readonly ICndClienteEstadual _cndEmpresaEstadual;
        private readonly IEmpresaRepository _empresaRepository;
        private readonly IEstadoRepository _estadoRepository;

        IEnumerable<Empresa>? listaEmpresas; //Lista enumerada
        IEnumerable<CndClienteEstadual>? listaCndEmpresasEstaduais; //Lista enumerada
        IEnumerable<Estado>? listaEstados; //lista de estados
        //Construtor
        public CndEstadualController(
            SefazToApiService sefazToApiService, 
            ICndClienteEstadual cndEmpresaEstadual,
            IEmpresaRepository empresaRepository,
            IEstadoRepository estadoRepository
            )
        {
            _sefazToApiService  = sefazToApiService;
            _cndEmpresaEstadual = cndEmpresaEstadual;
            _empresaRepository  = empresaRepository;
            _estadoRepository   = estadoRepository;
           

        }
        public async Task<IActionResult> Index(string cnpj, string razao, string cidade, string fantasia, string estado, int numPagina = 1)
        {
            this.listaEmpresas = await _empresaRepository.GetAllAsyncNoTracking();
            this.listaCndEmpresasEstaduais = await _cndEmpresaEstadual.GetAllAsyncNoTracking();
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();

            //Busca os Estados
            ViewBag.Estados = this.listaEstados.ToList();
            ViewBag.Empresas = this.listaEmpresas.ToList();
            return View(this.listaCndEmpresasEstaduais.ToPagedList(numPagina, 8));
        }

        //Metodo Get para Abrir a Página que vai receber os dados
        public async Task<IActionResult> ConsultarCnd()
        {
            this.listaEstados  = await _estadoRepository.GetAllAsyncNoTracking();
            this.listaEmpresas = await _empresaRepository.GetAllAsyncNoTracking();
            ViewBag.Empresas   = this.listaEmpresas.ToList();
            ViewBag.Estados    = this.listaEstados.ToList();
            return View();
        }

        
       

    }
}

PrecisoPRO/Controllers/CndFederalController.cs
using Microsoft.AspNetCore.Mvc;
using PrecisoPRO.Interfaces;
using PrecisoPRO.Models;
using PrecisoPRO.Services;
using X.PagedList;

namespace PrecisoPRO.Controllers
{
    public class CndFederalController : Controller
    {
        private readonly ICndClienteFederal _cndClienteFederal;
        private readonly IClienteRepository _clienteRepository;
        private readonly IEstadoRepository _estadoRepository;

        IEnumerable<Cliente>? listaClientes; //Lista enumerada
        IEnumerable<CndClienteFederal>? listaCndClientesFederais; //Lista enumerada
        IEnumerable<Estado>? listaEstados; //lista de estados


        public CndFederalController(
           ICndClienteFederal cndClienteFederal,
           IClienteRepository clienteRepository,
           IEstadoRepository estadoRepository
           )
        {
            _cndClienteFederal = cndClienteFederal;
            _clienteRepository = clienteRepository;
            _estadoRepository = estadoRepository;
        }
        public async Task<IActionResult> Index(string cnpj, string razao, string cidade, string estado, string status, int numPagina = 1)
        {
            this.listaClientes = await _clienteRepository.GetAllAsyncNoTracking();
            this.listaCndClientesFederais = await _cndClienteFederal.GetAllAsyncNoTracking();
            this.listaEstados = await _estadoRepository.GetAllAsyncNoTracking();

            //TO-DO -> FILTROS

            //Busca os Estados e empresas
            ViewBag.Estados = this.listaEstados.ToList();
            ViewBag.Clientes = this.listaClientes.ToList();
            return View(this.listaCndClientesFederais.ToPagedList(numPagina, 8));

            
        }

        //Atualizar todas as CNDS DAS EMPRESAS CADASTRADAS
    }
}

PrecisoPRO/Views/BuscarCNDs/Index.cshtml
@using PrecisoPRO.Models.ViewModels

@{
    Layout = "_Layout";
    ViewData["Title"] = "BuscarCNDs";
}
<div class="container-fluid">
   @*  <!--LINHA DO CARD PARA CND FEDRAL-->
    <div class="row">

    </div>

    <!--LINHA DO CARD PARA CND ESTADUAL-->
    <div class="row">

    </div> *@

    <div class="card" style="min-height: 95vh;">
        <div class="card-header">
           CERTIDÃO NEGATIVAS DE DÉBITOS
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND Federal
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>
                            <a asp-controller="CndFederal" asp-action="Index" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</a>
                            
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND Estadual
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>

                            <a asp-controller="CndEstadual" asp-action="Index" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND Municipal
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>

                            <button class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</button>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND Trabalhista
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>

                            <button class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</button>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND Fgts
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>

                            <button class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</button>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 mt-2">
                    <div class="card card-cnd">
                        <div class="card-header">
                            CND  RFB/PGFN
                        </div>
                        <div class="card-body">
                            <h5 class="fs-7"><span>0</span>Encontradas</h5>
                            <h5 class="fs-7"><span>0</span>Não baixada</h5>

                            <button class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check"></i> Listar</button>
                        </div>
                    </div>


                </div>
               
            </div>
            <div class="row mt-3">
                
               
            </div>



        </div>
    </div>
   
</div>

<section>
    <!-- MODAL-->
    <div class="modal fade" id="modal" aria-hidden="true">
    </div>
</section>